spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/graduationproject
      username: root
      password: zhang
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 50MB

server:
  port: 80
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
